apiVersion: apps/v1
kind: Deployment
metadata:
  name: koala-game-handler-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: koala-game-handler-service
  template:
    metadata:
      labels:
        app: koala-game-handler-service
    spec:
      restartPolicy: Always
      volumes:
        - name: redis-config
          configMap:
            name: redis-configmap
      containers:
        - name: koala-game-handler-service
          image: ykdbonteregistry.azurecr.io/koala-activity-game-handler-service:latest
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
        - name: redis
          image: redis:7.0.7-bullseye
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-configmap
                  key: host
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis-config
      imagePullSecrets:
          - name: ykdbonteregistry
volumes:
  - name: config
    configMap:
      name: koala-game-handler-service-config