name: Deploy to Azure Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'appsettings.json'
      env:
        ServiceBus.ConnectionString: ${{ secrets.SERVICE_BUS_CONNECTION_STRING }}
        Steam.ApiKey: ${{ secrets.STEAM_API_KEY }}
    - name: Login to azure
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build image
      run: |
        docker build -t${{ secrets.LOGIN_SERVER }}/koala-activity-game-handler-service:${{ github.sha }} .
        docker tag ${{ secrets.LOGIN_SERVER }}/koala-activity-game-handler-service:${{ github.sha }} ${{ secrets.LOGIN_SERVER }}/koala-activity-game-handler-service:latest
    - name: Push image
      run: |
        docker push ${{ secrets.LOGIN_SERVER }}/koala-activity-game-handler-service:latest
        docker push ${{ secrets.LOGIN_SERVER }}/koala-activity-game-handler-service:${{ github.sha }}
